name: myandroidbuild
on: [push]

jobs:

  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Android
      run: |
        cd AwesomeApp
        nuget restore
        cd AwesomeApp.Android
        msbuild AwesomeApp.Android.csproj /verbosity:normal /t:PackageForAndroid /p:Configuration=Debug
  
    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: "**/bin/Debug/com.companyname.AwesomeApp.apk"
  
  AppCenterDistibute:
    runs-on: ubuntu-latest
    needs: Android
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: my-artifact

    - name: App Center
      uses: wzieba/AppCenter-Github-Action@v1.0.0
      with:
        # App name followed by username 
        appName: Ch-DemoOrg/demoapp
        # Upload token - you can get one from appcenter.ms/settings
        token: ${{ secrets.AppCenterAPIToken }}
        # Distribution group
        group: alphatesters
        # Artefact to upload (.apk or .ipa)
        file: AwesomeApp/AwesomeApp.Android/bin/Debug/com.companyname.AwesomeApp.apk
        # Release notes visible on release page
        releaseNotes: "demo test"
